#
#   ██████╗██████╗ ██╗███╗  ██╗███╗  ██╗██╗███╗  ██╗
#  ██╔════╝██╔══██╗██║████╗ ██║████╗ ██║██║████╗ ██║
#  ╚█████╗░██████╔╝██║██╔██╗██║██╔██╗██║██║██╔██╗██║
#   ╚═══██╗██╔═══╝ ██║██║╚████║██║╚████║██║██║╚████║
#  ██████╔╝██║     ██║██║ ╚███║██║ ╚███║██║██║ ╚███║
#  ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚══╝╚═╝  ╚══╝╚═╝╚═╝  ╚══╝
#

database: "jdbc:sqlite:database.db"

messages:
  prefix: "§x§F§B§2§2§2§2H§x§F§C§4§5§2§Ao§x§F§D§6§8§3§2m§x§F§E§8§B§3§Ae§x§F§F§A§E§4§2s §7» "
  commands:
    player-only: "§x§F§B§3§E§3§E⚠ Este comando solo puede ser ejecutado por un jugador."
    gethomesitem-success: "&7Has recibido el objeto para establecer tu hogar."
    sethome-usage: "&cUso: /sethome <nombre>"
    sethome-success: "&a¡Hogar &e%name% &aestablecido con éxito!"
    sethome-error: "&c¡Ha ocurrido un error al establecer el hogar!"
    sethome-no-permission: "§x§F§B§3§E§3§E⚠ No tienes permiso para establecer un hogar."
    sethome-max-homes: "§x§F§B§3§E§3§E⚠ Has alcanzado el límite máximo de hogares permitidos &7[§x§A§F§8§7§F§B%max% Homes&7]."
    not-perms: "§x§F§B§3§E§3§E⚠ No tienes permisos para usar este comando."
    removehome-no-permission: "&§x§F§B§3§E§3§E⚠ No tienes permiso para eliminar un hogar."
    removehome-usage: "§x§F§B§3§E§3§E⚠ Uso: /removehome <nombre>"
    removehome-success: "&7Hogar §x§A§F§8§7§F§B%name% &7eliminado con éxito."
    removehome-error: "§x§F§B§3§E§3§E⚠ Ha ocurrido un error al eliminar el hogar"
    not-safety: "§x§F§B§3§E§3§E⚠ No se pudo encontrar una ubicación segura para teletransportarse."

  gui:
    home-deleted: "&7El hogar §x§A§F§8§7§F§B%name% &7ha sido eliminado."
    teleported: "&7Has sido teletransportado a §x§A§F§8§7§F§B%name%"
    teleport-cooldown: "§x§F§B§3§E§3§E⚠ Por favor, espera antes de teletransportarte nuevamente."
    move-cancel: "§x§F§B§3§E§3§E⚠ Teleportación cancelada debido a movimiento."
    teleporting: "&7Teletranspórtate a §x§A§F§8§7§F§B%name%&7 en solo 3 segundos! Permanece quieto durante el proceso."
    error: "§x§F§B§3§E§3§E⚠ Ha ocurrido un error al obtener los hogares."
    no-homes: "§x§F§B§3§E§3§E⚠ No tienes ningún hogar."